colors = [

    "Red",
    "Green",
    "Blue",
    "Yellow",
    "Cyan",
    "Magenta",
    "Black",
    "White",
    "Gray",
    "Brown",
    "Orange",
    "Purple",
    "Pink",
    "Teal",
    "Lavender",
    "Coral",
    "Turquoise",
    "Olive",
    "Peach",
    "Beige",
    "Plum",
    "Crimson",
    "Maroon",
    "Navy",
    "Gold",
    "Silver",
    "Indigo",
    "Mint",
    "Salmon",
    "Lime",
    "Aqua",
    "Sky Blue",
    "Sea Green",
    "Fuchsia",
    "Tan",
    "Slate Gray",
    "Mustard",
    "Chartreuse",
    "Lavender Blush",
    "Eggshell",
    "Copper",
    "Periwinkle",
    "Mahogany",
    "Cerulean",
    "Burgundy",
    "Wheat",
    "Ivory",
    "Honeydew",
    "Lavender Gray",
    "Eggplant",
    "Sienna",
    "Rust",
    "Charcoal",
    "Mauve",
    "Apricot",
    "Mint Green",
    "Berry",
    "Cobalt Blue",
    "Seafoam",
    "Cerulean Blue",
    "Electric Blue",
    "Peacock Blue",
    "Rose",
    "Amber",
    "Chartreuse Green",
    "Jade",
    "Raspberry",
    "Mulberry",
    "Burnt Orange",
    "Sage",
    "Cinnamon",
    "Vanilla",
    "Cobalt",
    "Wisteria",
    "Ash Gray",
    "Zaffre",
    "Onyx",
    "Topaz",
    "Lemon",
    "Grape",
    "Curry",
    "Emerald",
    "Midnight Blue",
    "Soft Pink",
    "Blush",
    "Coral Pink",
    "Electric Purple",
    "Fandango",
    "Dark Olive Green"


        ]