hobbys = [
    "Reading",
    "Traveling",
    "Cooking",
    "Gardening",
    "Photography",
    "Painting",
    "Drawing",
    "Writing",
    "Playing Musical Instruments",
    "Hiking",
    "Fishing",
    "Cycling",
    "Dancing",
    "Swimming",
    "Yoga",
    "Fitness",
    "Crafting",
    "Gaming",
    "Collecting (stamps, coins, etc.)",
    "Knitting",
    "Sewing",
    "Volunteering",
    "Birdwatching",
    "Playing Sports",
    "Surfing",
    "Rock Climbing",
    "Martial Arts",
    "Running",
    "Blogging",
    "Watching Movies",
    "Listening to Music",
    "Meditation",
    "Learning Languages",
    "Building Models",
    "Playing Chess",
    "Puzzle Solving",
    "Coding",
    "Home Brewing",
    "Embroidery",
    "Camping",
    "Horseback Riding",
    "Scuba Diving",
    "Martial Arts",
    "Woodworking",
    "Reading",
    "Traveling",
    "Cooking",
    "Gardening",
    "Photography",
    "Painting",
    "Drawing",
    "Writing",
    "Playing Musical Instruments",
    "Hiking",
    "Fishing",
    "Cycling",
    "Dancing",
    "Swimming",
    "Yoga",
    "Fitness",
    "Crafting",
    "Gaming",
    "Collecting (stamps, coins, etc.)",
    "Knitting",
    "Sewing",
    "Volunteering",
    "Birdwatching",
    "Playing Sports",
    "Surfing",
    "Rock Climbing",
    "Martial Arts",
    "Running",
    "Blogging",
    "Watching Movies",
    "Listening to Music",
    "Meditation",
    "Learning Languages",
    "Building Models",
    "Playing Chess",
    "Puzzle Solving",
    "Coding",
    "Home Brewing",
    "Embroidery",
    "Camping",
    "Horseback Riding",
    "Scuba Diving",
    "Woodworking",
    "Basketball",
    "Football",
    "Tennis",
    "Baseball",
    "Volleyball",
    "Soccer",
    "Rugby",
    "Golf",
    "Badminton",
    "Table Tennis",
    "Softball",
    "Cricket",
    "Swimming",
    "Ice Skating",
    "Snowboarding",
    "Skiing",
    "Running",
    "Ultimate Frisbee",
    "Lacrosse",
    "basketball"
    "football"
    "soccer"
    "cooking"
    "cook"
]